name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Version"
          files: |
            main.pdf
